# Import additional configuration files
import = ["~/.config/alacritty/kanagawa.toml"]

[env]
TERM = "xterm-256color"

[window]
padding = { x = 4, y = 4 }

[font]
normal = { family = "JetBrainsMono NFM", style = "Medium" }
size = 8
