theme = "kanagawa-dragon"

[editor]
line-number = "relative"
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
"S-up" = "page_up"
"S-down" = "page_down"
