[[language]]
name = "nix"
formatter = { command = "nixfmt" }
auto-format = true

[language-server.rust-analyzer.config]
check = { command = "clippy" }

[[language]]
name = "svelte"
auto-format = true

[[language]]
name = "python"
language-servers = ["ty", "ruff", "basedpyright"]
auto-format = true

[[language]]
name = "javascript"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "babel"] }
language-servers = [{ name = "typescript-language-server" }]

[[language]]
name = "jsx"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "babel"] }
language-servers = [{ name = "typescript-language-server" }]

[[language]]
name = "typescript"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "typescript"] }
language-servers = [{ name = "typescript-language-server" }]

[[language]]
name = "tsx"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "babel-ts"] }
language-servers = [{ name = "typescript-language-server" }]
