# Import additional configuration files
# import = ["~/.config/alacritty/kanagawa-dragon.toml"]

[env]
TERM = "xterm-256color"

[window]
padding = { x = 4, y = 4 }

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Medium" }
size = 8
