require('after/plugin/lsp')
require('after/plugin/dapui')
require('after/plugin/harpoon')
require('after/plugin/telescope')
require('after/plugin/treesitter')
require('after/plugin/neo-tree')
require('after/plugin/lualine')
require('after/plugin/kanagawa')
