require('after/plugin/harpoon')
require('after/plugin/telescope')
require('after/plugin/treesitter')
require('after/plugin/nvim-tree')
require('after/plugin/lsp-zero')
require('after/plugin/lualine')
require('after/plugin/kanagawa')
