require('plugins/nvim-telescope')
require('plugins/nvim-cmp')
require('plugins/nvim-lspconfig')
require('plugins/nvim-indent-blankline')
require('plugins/nvim-treesitter')
require('plugins/nvim-tree')
